export const ROUTES = {
  LOGIN: '/login',
  REGISTER: '/login',
  DASHBOARD: '/dashboard',
  ATTENDANCE: '/attendance',
  ATTENDANCE_HISTORY: '/attendance/history',
  LEAVE_APPLY: '/leave/apply',
  LEAVE_HISTORY: '/leave/history',
  LEAVE_BALANCE: '/leave/balance',
  MANAGER_APPROVALS: '/manager/approvals',
  MANAGER_TEAM: '/manager/team',
  MANAGER_KYC: '/manager/kyc-approvals',
  HR_ANALYTICS: '/hr/analytics',
  HR_ATTENDANCE_REPORT: '/hr/reports/attendance',
  HR_LEAVE_REPORT: '/hr/reports/leaves',
  ADMIN_USERS: '/admin/users',
  KYC: '/kyc',
  NOT_FOUND: '/404',
  FORBIDDEN: '/403',
};

export const ROLE_ROUTES = {
  EMPLOYEE: [ROUTES.DASHBOARD, ROUTES.ATTENDANCE, ROUTES.ATTENDANCE_HISTORY, ROUTES.LEAVE_APPLY, ROUTES.LEAVE_HISTORY, ROUTES.LEAVE_BALANCE, '/kyc'],
  MANAGER: [ROUTES.DASHBOARD, ROUTES.MANAGER_APPROVALS, ROUTES.MANAGER_TEAM, ROUTES.MANAGER_KYC, ROUTES.LEAVE_APPLY, ROUTES.LEAVE_BALANCE, ROUTES.LEAVE_HISTORY, ROUTES.ATTENDANCE_HISTORY],
  HR: [ROUTES.DASHBOARD, ROUTES.HR_ANALYTICS, ROUTES.HR_ATTENDANCE_REPORT, ROUTES.HR_LEAVE_REPORT, ROUTES.LEAVE_HISTORY],
  ADMIN: [ROUTES.DASHBOARD, ROUTES.ADMIN_USERS],
};
